### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by NinaOmejc** [the-virtual-brain/tvb-widgets#54]
Hi,
I have been trying to install the tvb-widgets on Ubuntu 22.04 by installing it in a clean virtual environment but I encounter two issues.

First one is related to the installation of jupyter extensions. I installed jupyterlab, nodejs (version 20.1.0), npm (version 9.6.4) but I get the errors such as ""jupyter-matplotlib" is not a valid npm package".  

Second one is related to the installation of pip install tvb-widgets. They are installed succesfully but when I try to import api, i get the error below. 

Are errors independent or related? 

Is it possible to use tvb-widgets also just in general IDE (e.g. Pycharm) not a Jupyter notebook?

Thanks! 

>>> import tvbwidgets.api as api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ninaomejc/PycharmProjects/testTVBwidgets/venv/lib/python3.10/site-packages/tvbwidgets/api.py", line 13, in <module>
    from .ui.pse_launcher_widget import PSELauncher, HPCConfig
  File "/home/ninaomejc/PycharmProjects/testTVBwidgets/venv/lib/python3.10/site-packages/tvbwidgets/ui/pse_launcher_widget.py", line 13, in <module>
    from tvbwidgets.core.hpc.config import HPCConfig
ModuleNotFoundError: No module named 'tvbwidgets.core.hpc'

**Comment by liadomide** [comment]
Hi @NinaOmejc ,

The 2 issues seem not to be related.

I can reproduce your import error with the previous `tvb-widgets` release. 
Please try a `pip install -U tvb-widgets`
It should bring you tvb-widgets version `1.4.1` where that import is fixed.

For preparing your env, have you looked in this repo at `prepare_env` scripts from this folder https://github.com/the-virtual-brain/tvb-widgets/tree/main/dev ?
We have Python 3.8 there as example because EBRAINS lab is using it, but it should be fine with another version also.

Have you considered using widgets directly from EBRAINS lab  https://lab.ebrains.eu/ (no plugin installation will be needed there)? 
You would need to register for an EBRAINS account first. https://www.ebrains.eu/page/sign-up

Yes, you should be able to use tvb-widgets from PyCharm, but then maybe you want to do a checkout of this github repo and link from sources.

I hope the above can help you a bit.

Best,
Lia.

**Comment by NinaOmejc** [comment]
Dear Lia,

thank you for your reply! 
I have missed this dev/prepare.sh file. Calling it before installing tvb-widgets package through Pycharm solved (both of) my installation problems, thanks!
